language: generic

matrix:
  include:
    - os: linux
      services: docker
      before_install:
        - docker pull swift:5.0
      script:
        - docker run -v "$(pwd):/root/aws-signer" swift:5.0 /bin/sh -c "apt-get -q -y install libssl-dev zlib1g-dev && cd /root/aws-signer && swift build && swift test --parallel -Xswiftc -DDEBUG"
    - os: osx
      language: swift
      osx_image: xcode10.2
      script:
        - swift build
        - swift test --parallel -Xswiftc -DDEBUG
