name: CI

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build and Test
      run: swift test
      
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['5.1', '5.2']
    container:
      image: swift:${{ matrix.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata zlib1g-dev
    - name: Build and Test
      run: swift test
    
